# Generated by Django 6.0.7

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_prescription_doctorappointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('painfever', 'Pain & Fever'), ('vitamins', 'Vitamins'), ('coldcough', 'Cold & Cough'), ('diabetes', 'Diabetes Care'), ('firstaid', 'First Aid'), ('skincare', 'Skin Care'), ('babycare', 'Baby Care'), ('devices', 'Devices & Monitors')], max_length=20)),
                ('label', models.CharField(blank=True, help_text='Small text shown above the product name, e.g. PAIN & FEVER', max_length=50)),
                ('description', models.CharField(blank=True, help_text='e.g. 500mg · Strip of 15 Tablets', max_length=255)),
                ('price', models.PositiveIntegerField(help_text='Price in ₹')),
                ('old_price', models.PositiveIntegerField(blank=True, help_text='Original price in ₹ (optional, shown struck-through)', null=True)),
                ('tag', models.CharField(choices=[('OTC', 'OTC'), ('Rx', 'Rx (Prescription Required)')], default='OTC', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('stock', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this product from the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
